name: awsilny_driver
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter 

  firebase_core: ^1.19.1
  firebase_auth: ^3.4.1
  cloud_firestore: ^3.2.1
  provider: ^6.0.3
  flutter_spinkit: ^5.1.0
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/icons/app_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
     - images/
